config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: "login", sign_out: "logout", sign_up: "register"}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/views/shared/_app_footer.html.erb
<div class="mastfoot app-footer">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_app_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Evil Genius</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper  "nav-link" %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Development blog</h1>
    <p class="lead blog-description">Going ons with the development and technologies that we use.</p>
    <%= link_to 'Write a new blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>This is a Development blog of Evil Genius studio. The contents of the blog are ment to give you, the reader, an idea of what we do, how we do it. It also gives you a chance to interact with us directly.</p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled media-link">
      <li><a href="#"><%= fa_icon "github 2x" %></a></li>
      <li><a href="#"><%= fa_icon "facebook 2x" %></a></li>
      <li><a href="#"><%= fa_icon "instagram 2x" %></a></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolios", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-left">
      <%= copyright_generator %>
    </p>
    <p class="float-right">
      <%= link_to 'Portfolios', portfolios_path %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Evil Genius portfolio</h1>
    <p class="lead text-muted">This is the portfolio contining some of the projects that Evil Genius studio has created. In line with our mission we strive to make our apps beautiful, easy to use and functional. Each portfolio item contains information and images that relate to the specific project.</p>
    <p>
      <%= link_to 'About me', about_path, class: "btn btn-primary" %>
      <%= link_to 'Blog', blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">Evil Genius portfolio</h4>
        <p class="text-muted">Design and functionality have to go hand in hand. It is our mission to create beautiful and functinal envoroments for users to enhance user expirience and not demish it.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Evil Genius</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>